## all requests to /ws/ → Daphne on 5000

location /ws/ {
    proxy_pass          http://127.0.0.1:5000;
    proxy_http_version  1.1;

    # WebSocket handshake headers
    proxy_set_header    Upgrade             $http_upgrade;
    proxy_set_header    Connection          "upgrade";
    proxy_set_header    Host                $host;
}
